$.lang = {};

$.lang.ko = {
  permanent_1: "통상",
  limited_1: "한정",
  twilight_1: "트와코레",
  mysongs_1: "마이코레",
  parallel_1: "파라코레",
  event_1: "이벤트",
  fes_1: "페스",
  campaign_1: "캠페인",
  other_1: "기타",
  permanent_2: "통상 (" + CARD_TYPE_CHAR.permanent + ")",
  limited_2: "한정 (" + CARD_TYPE_CHAR.limited + ")",
  twilight_2: "트와코레 (" + CARD_TYPE_CHAR.twilight + ")",
  mysongs_2: "마이코레 (" + CARD_TYPE_CHAR.mysongs + ")",
  parallel_2: "파라코레 (" + CARD_TYPE_CHAR.parallel + ")",
  event_2: "이벤트 (" + CARD_TYPE_CHAR.event + ")",
  fes_2: "페스 (" + CARD_TYPE_CHAR.fes + ")",
  campaign_2: "캠페인 (" + CARD_TYPE_CHAR.campaign + ")",
  other_2: "기타 (" + CARD_TYPE_CHAR.other + ")",
  startBaseDate: "시작일:",
  endBaseDate: "종료일:",
  firstImplementation: "첫 실장",
  interval: "간격",
  intervalDate: "간격일",
  showFesIcon: "페스 일러스트로 표시",
  name: "이름",
  rank: "순위",
  pFirstImplementNote: "※ P카드의 첫 실장일은 「白いツバサ」 실장일이 기준일",
  sFirstImplementNote: "※ S카드의 첫 실장일은 「283プロのヒナ」 실장일이 기준일",
  allFirstImplementNote: "※ 모든 카드의 첫 실장일은 「白いツバサ」 실장일이 기준일",
  showIcon: "아이콘 표시",
  showRCard: "첫 실장 비표시",
  showRerun: "한정 복각 표시",
  selShowRerun0: "비표시",
  selShowRerun1: "복각 표시",
  selShowRerun2: "미복각 표시",
  selShowRerun3: "모두 표시",
  showCardCount: "카드 수 표시",
  showChangeCardLap: "카드 차수 변경 표시",
  allChk: "전체 체크",
  datePreset: "기준일 설정 프리셋",
};

$.lang.ja = {
  permanent_1: "恒常",
  limited_1: "限定",
  twilight_1: "トワコレ",
  mysongs_1: "マイコレ",
  parallel_1: "パラコレ",
  event_1: "イベント",
  fes_1: "フェス",
  campaign_1: "キャンペーン",
  other_1: "その他",
  permanent_2: "恒常 (" + CARD_TYPE_CHAR.permanent + ")",
  limited_2: "限定 (" + CARD_TYPE_CHAR.limited + ")",
  twilight_2: "トワコレ (" + CARD_TYPE_CHAR.twilight + ")",
  mysongs_2: "マイコレ (" + CARD_TYPE_CHAR.mysongs + ")",
  parallel_2: "パラコレ (" + CARD_TYPE_CHAR.parallel + ")",
  event_2: "イベント (" + CARD_TYPE_CHAR.event + ")",
  fes_2: "フェス (" + CARD_TYPE_CHAR.fes + ")",
  campaign_2: "キャンペーン (" + CARD_TYPE_CHAR.campaign + ")",
  other_2: "その他 (" + CARD_TYPE_CHAR.other + ")",
  startBaseDate: "開始日:",
  endBaseDate: "終了日:",
  firstImplementation: "初実装",
  interval: "間隔",
  intervalDate: "間隔日",
  showFesIcon: "フェスイラストで表示",
  name: "名前",
  rank: "順位",
  pFirstImplementNote: "※ Pカードの初実装日は「白いツバサ」の実装日が基準日",
  sFirstImplementNote: "※ Sカードの初実装日は「283プロのヒナ」の実装日が基準日",
  allFirstImplementNote: "※ すべてのカードの初実装日は「白いツバサ」の実装日が基準日",
  showIcon: "アイコン表示",
  showRCard: "初実装 非表示",
  showRerun: "限定復刻表示",
  selShowRerun0: "非表示",
  selShowRerun1: "復刻あり表示",
  selShowRerun2: "復刻なし表示",
  selShowRerun3: "すべて表示",
  showCardCount: "カード数表示",
  showChangeCardLap: "カード周目変更表示",
  allChk: "すべてチェック",
  datePreset: "基準日設定プリセット",
};
