$.lang = {};

$.lang.ko = {
  permanent: "통상",
  limited: "한정",
  event: "이벤트",
  fes: "페스",
  campaign: "캠페인",
  startBaseDate: "시작일:",
  endBaseDate: "종료일:",
  firstImplementation: "첫 실장",
  interval: "간격",
  intervalDate: "간격일",
  casual: "사복",
  name: "이름",
  rank: "순위",
  pFirstImplementNote: "※ P카드의 첫 실장일은 「白いツバサ」 실장일이 기준일",
  sFirstImplementNote: "※ S카드의 첫 실장일은 「283プロのヒナ」 실장일이 기준일",
  allFirstImplementNote: "※ 모든 카드의 첫 실장일은 「白いツバサ」 실장일이 기준일",
  showIcon: "아이콘 표시",
  showRCard: "첫 실장 비표시",
};

$.lang.ja = {
  permanent: "恒常",
  limited: "限定",
  event: "イベント",
  fes: "フェス",
  campaign: "キャンペーン",
  startBaseDate: "開始日:",
  endBaseDate: "終了日:",
  firstImplementation: "初実装",
  interval: "間隔",
  intervalDate: "間隔日",
  casual: "私服",
  name: "名前",
  rank: "順位",
  pFirstImplementNote: "※ Pカードの初実装日は「白いツバサ」の実装日が基準日",
  sFirstImplementNote: "※ Sカードの初実装日は「283プロのヒナ」の実装日が基準日",
  allFirstImplementNote: "※ すべてのカードの初実装日は「白いツバサ」の実装日が基準日",
  showIcon: "アイコン表示",
  showRCard: "初実装 非表示",
};
