$.lang = {};

$.lang.ko = {
  permanent_1: "통상",
  limited_1: "한정",
  twilight_1: "트와코레",
  mysongs_1: "마이코레",
  parallel_1: "파라코레",
  event_1: "이벤트",
  fes_1: "페스",
  campaign_1: "캠페인",
  other_1: "기타",
  permanent_2: "통상 (P)",
  limited_2: "한정 (L)",
  twilight_2: "트와코레 (Tw)",
  mysongs_2: "마이코레 (My)",
  parallel_2: "파라코레 (Pa)",
  event_2: "이벤트 (E)",
  fes_2: "페스 (F)",
  campaign_2: "캠페인 (C)",
  other_2: "기타 (O)",
  startBaseDate: "시작일:",
  endBaseDate: "종료일:",
  firstImplementation: "첫 실장",
  interval: "간격",
  intervalDate: "간격일",
  showFesIcon: "페스 일러스트로 표시",
  name: "이름",
  rank: "순위",
  pFirstImplementNote: "※ P카드의 첫 실장일은 「白いツバサ」 실장일이 기준일 (하즈키는 제외)",
  sFirstImplementNote: "※ S카드의 첫 실장일은 「283プロのヒナ」 실장일이 기준일 (하즈키는 제외)",
  allFirstImplementNote: "※ 모든 카드의 첫 실장일은 「白いツバサ」 실장일이 기준일 (하즈키는 제외)",
  showIcon: "아이콘 표시",
  showRCard: "첫 실장 비표시",
  showCardCount: "카드 수 표시",
  showChangeCardLap: "카드 차수 변경 표시",
  allChk: "전체 체크",
  datePreset: "기준일 설정 프리셋",
};

$.lang.ja = {
  permanent_1: "恒常",
  limited_1: "限定",
  twilight_1: "トワコレ",
  mysongs_1: "マイコレ",
  parallel_1: "パラコレ",
  event_1: "イベント",
  fes_1: "フェス",
  campaign_1: "キャンペーン",
  other_1: "その他",
  permanent_2: "恒常 (P)",
  limited_2: "限定 (L)",
  twilight_2: "トワコレ (Tw)",
  mysongs_2: "マイコレ (My)",
  parallel_2: "パラコレ (Pa)",
  event_2: "イベント (E)",
  fes_2: "フェス (F)",
  campaign_2: "キャンペーン (C)",
  other_2: "その他 (O)",
  startBaseDate: "開始日:",
  endBaseDate: "終了日:",
  firstImplementation: "初実装",
  interval: "間隔",
  intervalDate: "間隔日",
  showFesIcon: "フェスイラストで表示",
  name: "名前",
  rank: "順位",
  pFirstImplementNote: "※ Pカードの初実装日は「白いツバサ」の実装日が基準日 (はづきは除く)",
  sFirstImplementNote: "※ Sカードの初実装日は「283プロのヒナ」の実装日が基準日 (はづきは除く)",
  allFirstImplementNote:
    "※ すべてのカードの初実装日は「白いツバサ」の実装日が基準日 (はづきは除く)",
  showIcon: "アイコン表示",
  showRCard: "初実装 非表示",
  showCardCount: "カード数表示",
  showChangeCardLap: "カード周目変更表示",
  allChk: "すべてチェック",
  datePreset: "基準日設定プリセット",
};
